version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - bandvov
  labels:
  - dependabot
  - dependency update
  ignore:
  - dependency-name: cypress
    versions:
    - 7.0.1
    - 7.1.0
