version: 2
jobs:
  test:
    docker:
      -
        image: 'circleci/node:10.8.0'
    working_directory: ~/app-name-directory
    steps:
      - checkout
      -
        restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      -
        run: 'yarn install'
      -
        save_cache:
          name: Save Yarn Package Cache
          key: 'yarn-packages-{{ checksum "yarn.lock" }}'
          paths:
            - ~/.cache/yarn
      -
        run: 'yarn test'
  deploy_prod:
    working_directory: ~/app-name-directory
    docker:
      -
        image: 'circleci/node:10.8.0'
    steps:
      - checkout
      -
        run:
          name: 'Build Application'
          command: yarn install && yarn run build && yarn run generate-zip
      -
        run:
          name: 'Install Python'
          command: "sudo apt-get -y -qq update\nsudo apt-get -y -qq install python3.4-dev\necho 'export PATH=/root/.local/bin/:$PATH' >> $BASH_ENV\necho 'export PATH=/home/circleci/.local/bin/:$PATH' >> $BASH_ENV\n"
      -
        run:
          name: 'Install pip'
          command: "curl -O https://bootstrap.pypa.io/get-pip.py\npython3.4 get-pip.py --user\n"
      -
        run:
          name: 'Install AWS EB CLI & S3 CLI'
          command: "pip install awsebcli --upgrade --user\npip install awscli --upgrade --user\n"

workflows:
  version: 2
  Test_and_Deploy:
    jobs:
      - test
      -
        deploy_prod:
          requires:
            - test
          filters:
            branches:
              only: main