version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          build: yarn build
          start: yarn start
      - cypress/run:
          requires:
            - cypress/install
          test: yarn test
          yarn: true  
       
