version: 2.1
orbs:
  cypress: cypress-io/cypress@1 
workflows:
  build:
    jobs:
      - cypress/install:
          yarn: true
          build: yarn build
      - cypress/run:
          yarn: true
          name: 4 machines
          requires:
            - cypress/install
          parallel: true
          parallelism: 4
          group: 4 machines
          start: yarn start
          wait-on: 'http://localhost:3000'
    
