version: 2.1
orbs:
  cypress: cypress-io/cypress@1 
workflows:
  build:
    jobs:
      - cypress/install:
          build: yarn build
      - cypress/run:
          yarn: true
          requires:
            - cypress/install
          start: yarn start
          wait-on: 'http://localhost:3000'
    
