# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      

    - name: Installing my packages  
      run: npm ci

    - name: Build my App  
      run: npm build
    - name: Export App
      run: npm run export 
    
    - name: Deploy my App    
      uses: crazy-max/ghaction-github-pages@v2
      with:
          target_branch: gh-pages
          build_dir: out
      env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
