
name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      

    - name: Installing my packages
      run: yarn install

    - name: Build my App  
      run: yarn build
      run: yarn start

    - name: Cypress run 🧪
          uses: cypress-io/github-action@v2
          with:
            yarn: true
            command: yarn e2e